# Generated by Django 3.2.16 on 2022-11-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_data_migration"),
        ("mainapp", "0003_my_data_migration"),
    ]

    operations = []
